[tool.poetry]
name = "fastapi-app"
version = "0.1.0"
description = ""
authors = ["Kirill"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.83.0"
uvicorn = "^0.18.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
